# =============================================================================
# Prooflayer PowerShell scanner — third app registration (cert-based app-only)
#
# Why a THIRD app registration:
#
# - prooflayer-scanner          (main.tf):  Graph app-only,    client_secret
# - prooflayer-scanner-delegated (delegated.tf):
#                                            Graph delegated,  refresh_token
# - prooflayer-scanner-pwsh      (this file):
#                                            Exchange app-only, X.509 cert
#
# Microsoft expects unattended PowerShell against IPPSSession /
# Connect-ExchangeOnline to use a dedicated app registration with:
#   1. Exchange.ManageAsApp (Application permission on Office 365
#      Exchange Online API — NOT on Microsoft Graph) granted with
#      admin consent
#   2. An X.509 certificate uploaded as a keyCredential on the app
#   3. The corresponding service principal added to a Security &
#      Compliance role group via `Add-RoleGroupMember` from
#      Connect-IPPSSession (one-time, post-apply)
#
# Three separation rationale:
#   - Blast radius: a leaked cert here only grants Exchange/compliance
#     RBAC, not Graph identity reads (and vice versa for the other SPNs)
#   - Audit clarity: each SPN's sign-in log entries are scoped to one
#     auth flavor — easier to spot anomalies
#   - Microsoft pattern: their docs explicitly recommend separate apps
#     for confidential vs public clients vs cert-only-confidential
#
# Key material strategy:
#   The cert + key are terraform-generated via the tls provider and
#   uploaded to Azure as an azuread_application_certificate. The
#   private key lives in terraform state, NOT in git, NOT in any
#   secrets store — operator pulls it via `terraform output -raw
#   pwsh_private_key` and pastes into Prooflayer's credential form
#   (same shape as ssh_key credentials).
#
#   Rotation: bump `tls_self_signed_cert.scanner_pwsh.validity_period_hours`,
#   `terraform apply`, retrieve new outputs, paste new values into the
#   Prooflayer credential (rotate-credential flow).
#
#   For tenants where the TF-state-holding-private-key trade-off is
#   unacceptable (3PAO customer tenants), swap this whole file for an
#   external-cert variant: drop the tls_* resources, change the
#   azuread_application_certificate value to a `var.pwsh_certificate_pem`
#   variable, and the operator provides cert.pem from openssl out-of-band.
# =============================================================================

data "azuread_service_principal" "exchange_online" {
  client_id = "00000002-0000-0ff1-ce00-000000000000" # Office 365 Exchange Online
}

# -----------------------------------------------------------------------------
# Key material — generated by terraform, paste-able as PEMs into Prooflayer
# -----------------------------------------------------------------------------

resource "tls_private_key" "scanner_pwsh" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_self_signed_cert" "scanner_pwsh" {
  private_key_pem = tls_private_key.scanner_pwsh.private_key_pem

  subject {
    common_name  = var.pwsh_spn_display_name
    organization = "Prooflayer"
  }

  # 1 year. Re-apply terraform after this to rotate; the
  # azuread_application_certificate below picks up the new cert
  # automatically, then operator updates the Prooflayer credential
  # via the rotate flow.
  validity_period_hours = var.pwsh_cert_validity_hours

  # Standard server-cert uses. `digital_signature` is the load-bearing
  # one for Microsoft's cert-auth flow; the other two are conventional
  # additions that don't hurt.
  allowed_uses = [
    "digital_signature",
    "key_encipherment",
    "server_auth",
  ]
}

# -----------------------------------------------------------------------------
# App registration + service principal
# -----------------------------------------------------------------------------

resource "azuread_application" "scanner_pwsh" {
  display_name     = var.pwsh_spn_display_name
  sign_in_audience = "AzureADMyOrg"

  required_resource_access {
    resource_app_id = "00000002-0000-0ff1-ce00-000000000000" # Office 365 Exchange Online

    resource_access {
      # Exchange.ManageAsApp — application permission for unattended
      # PowerShell. Global Exchange Online permission ids:
      # dc50a0fb-09a3-484d-be87-e023b12c6440
      id   = "dc50a0fb-09a3-484d-be87-e023b12c6440"
      type = "Role" # "Role" = Application permission; "Scope" = Delegated.
    }
  }

  # NO public_client block — confidential client (cert-only).
  # NO password block — the cert is the sole credential.
}

resource "azuread_service_principal" "scanner_pwsh" {
  client_id = azuread_application.scanner_pwsh.client_id

  # enterprise = true so it shows up in Entra → Enterprise applications
  # — needed because the Security & Compliance Center's
  # `Add-RoleGroupMember` cmdlet looks for the SPN in that view.
  feature_tags {
    enterprise = true
    gallery    = false
  }
}

# -----------------------------------------------------------------------------
# Bind the cert to the app
#
# `azuread_application_certificate` uploads ONLY the public certificate
# half (PEM, the public key + signature) as a keyCredential on the app
# registration. Azure verifies signed JWT assertions during cert-auth
# token exchange by checking the assertion's signature against this
# public key. The private key never leaves the operator side (and our
# TF state, until it gets pasted into Prooflayer's credential vault).
# -----------------------------------------------------------------------------

resource "azuread_application_certificate" "scanner_pwsh" {
  application_id = azuread_application.scanner_pwsh.id
  type           = "AsymmetricX509Cert"
  value          = tls_self_signed_cert.scanner_pwsh.cert_pem
  end_date       = tls_self_signed_cert.scanner_pwsh.validity_end_time
}

# -----------------------------------------------------------------------------
# Admin consent for Exchange.ManageAsApp
# -----------------------------------------------------------------------------

resource "azuread_app_role_assignment" "scanner_pwsh_exchange_manageasapp" {
  app_role_id         = "dc50a0fb-09a3-484d-be87-e023b12c6440"
  principal_object_id = azuread_service_principal.scanner_pwsh.object_id
  resource_object_id  = data.azuread_service_principal.exchange_online.object_id
}
